version: '3.9'

services:
  my_runner:
    restart: unless-stopped
    image: myoung34/github-runner
    environment:
      RUNNER_NAME: my-runner
      RUNNER_SCOPE: repo
      REPO_URL: https://github.com/codequokka/github-actions-self-hosted-runner-example
      LABELS: my-runner
      ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
