name: Sample

on:
  push:

jobs:
  echo_hostname:
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Echo host name
        run: echo $(hostname)

      - name: Checkout the repo
        uses: actions/checkout@v3
