name: Sample

on:
  push:

jobs:
  echo_hostname:
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Echo host name
        run: echo $(hostname)

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/playbook.yml
          options: |
            --inventory ./ansible/hosts.ini
